---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  ignore_errors: yes
  tasks: 
    - name: New tasks
      package:
        name: httpd
        state: installed

    - name: Add user
      user:
        name: bob
        state: present

    - name: Add group
      group:
        name: managers
        state: present

    - name: Create file
      file:
        path: /tmp/testfile1
        state: touch
        mode: 0755
        group: managers
        owner: bob
        

